### ISSUE TITLE
run_snpable2.sh: splitfa and gen_mask

### ISSUE THREAD

**Issue by yangwukaidi** [jessicarick/msmc2_scripts#1]
hi！
Thank you for sharing.
I ran into a difficulty when using this script，run_snpable2.sh.
The script always prompts that splitfa and gen_mask cannot be found when it runs. 
But I'm pretty sure that the two executables are in the current running directory.
How will this problem be solved?
Looking forward to hearing from you!

**Comment by jessicarick** [comment]
Hello! In the `run_snpable2.sh` script, the first two lines of code indicate where the executables can be found. Have you changed these two lines? If you have the executables in the same directory, I would just comment out these two lines (lines 5-6). Hope that helps!

**Comment by jessicarick** [comment]
Hi @yangwukaidi, were you able to get the scripts working? I'm going to close this issue, but please re-open it and let me know if you're still having problems.
